Add GraphQL support
venusvavadiya/simple-jira pull request #16
Opened 2021-04-01 20:14 UTC by shailscript

2021-04-07 16:52 UTC, venusvavadiya commented on apps/web/src/app/app.module.ts
> +      autoSchemaFile: 'schema.gql',
Why are we generating file instead of doing it in-memory?

2021-04-09 03:32 UTC, shailscript commented on apps/web/src/app/app.module.ts
> +      autoSchemaFile: 'schema.gql',
I wasn't aware of the in-memory schema generation. Pushing an update with the requested changes.

2021-04-12 23:14 UTC, venusvavadiya requested changes

2021-04-12 23:14 UTC, venusvavadiya commented on apps/web/src/app/projects.resolver.ts
> +  CreateProjectCommandHandler, RenameProjectCommand,
```suggestion
  CreateProjectCommandHandler,
  RenameProjectCommand,
```

2021-04-12 23:14 UTC, venusvavadiya commented on apps/web/src/app/projects.resolver.ts
> +/* eslint-disable class-methods-use-this */
```suggestion
```

2021-04-12 23:14 UTC, venusvavadiya commented on apps/web/src/app/projects.resolver.ts
> +  @Mutation((returns) => String)
```suggestion
  @Mutation((returns) => string)
```

2021-04-12 23:14 UTC, venusvavadiya commented on apps/web/src/app/projects.resolver.ts
> +  @Mutation((returns) => String)
```suggestion
  @Mutation((returns) => string)
```

2021-04-12 23:14 UTC, venusvavadiya commented on apps/web/src/app/projects.resolver.ts
> +  }
```suggestion
```

Don't need query in this PR.

2021-04-12 23:14 UTC, venusvavadiya commented on apps/web/src/app/projects.resolver.ts
> +} from '@nestjs/graphql';
```suggestion
import { Args, Mutation, Resolver } from '@nestjs/graphql';
```

2021-04-12 23:14 UTC, venusvavadiya commented on apps/web/src/app/app.module.ts
> +      path: 'projects',
What is the default value for this? We should not be using `projects` here.

2021-04-13 03:24 UTC, shailscript commented on apps/web/src/app/app.module.ts
> +      path: 'projects',
Default is `/graphql`

2021-04-13 04:05 UTC, shailscript commented on apps/web/src/app/app.module.ts
> +      path: 'projects',
Updated to be default, [reference](https://graphql.org/learn/serving-over-http/).

2021-04-16 02:28 UTC, venusvavadiya requested changes

2021-04-16 20:36 UTC, shailscript commented on apps/web/src/app/app.module.ts
> +      autoSchemaFile: true,
It isn't set by default.
Error: `Apollo Server requires either an existing schema, modules or typeDefs`

2021-05-01 22:29 UTC, closed without merging